; Copyright(C) 2025-2026 Advanced Micro Devices, Inc. All rights reserved.
; SPDX-License-Identifier: MIT
;
; GAIA Agent UI — custom NSIS installer additions.
;
; This file is `include`d by the electron-builder-generated NSIS script.
; It writes the Windows autostart registry entry so GAIA Agent UI starts
; on user login (default ON, matching Slack/Discord/Zoom convention per
; plan §4.1), and cleans up that registry entry on uninstall.
;
; ─── Why "always on" instead of a finish-page checkbox ──────────────────
;
; An earlier revision of this file used MUI_FINISHPAGE_SHOWREADME_FUNCTION
; to display a "Start GAIA when I sign in to Windows" checkbox on the
; finish page. That approach is incompatible with electron-builder's
; standard page flow: electron-builder emits BOTH MUI_PAGE_FINISH and
; MUI_UNPAGE_FINISH, and the finish-page macro is shared between them.
; If MUI_FINISHPAGE_SHOWREADME_FUNCTION points at a globally-named
; function (e.g. `GaiaSetAutoStart`), the uninstaller's finish page tries
; to `Call GaiaSetAutoStart` — but NSIS requires all functions called
; from the uninstall section to be prefixed with `un.`. The build fails
; with:
;
;   Call must be used with function names starting with "un." in the uninstall section.
;
; Fixing this by defining a parallel `un.GaiaSetAutoStart` doesn't work
; either — NSIS prohibits using `!undef` on MUI macro-reserved symbols
; between the two page insertions when they're both emitted by a parent
; script we don't control. The simplest robust fix is to drop the
; checkbox entirely and write the autostart key unconditionally. This
; matches the plan's "default ON" intent and mirrors how Slack/Discord
; behave. Users who want to disable autostart can:
;
;   1. Use the GAIA Agent UI tray menu → Settings → "Launch at login"
;      (see services/tray-manager.cjs)
;   2. Or disable via Windows Task Manager → Startup tab
;   3. Or delete the HKCU Run key manually with regedit
;
; electron-builder exposes extension macros we hook into:
;
;   customInstall    — runs at the end of the main install section
;   customUnInstall  — runs at the start of the uninstall section
;
; Reference: https://github.com/electron-userland/electron-builder

; ─── File-scope includes ───────────────────────────────────────────────
;
; LogicLib provides ${If}/${ElseIf}/${Else}/${EndIf} used by the Lemonade
; MSI install branch in customInstall (issue #774). version.nsh is
; generated by `python src/gaia/version.py` during CI and exposes
; ${LEMONADE_VERSION} for the DetailPrint message.
;
; Both !include directives MUST be at file scope, not inside a !macro.
; electron-builder's NSIS template may expand customInstall more than
; once, which would cause "already defined" errors if includes were
; placed inside the macro body.
;
; version.nsh is resolved via ${BUILD_RESOURCES_DIR} (the injected -D
; define that also drives the File directive on line 91). Using the
; bare path "installer\version.nsh" would only work if NSIS is run from
; the repo root — electron-builder runs it from a temp directory, so
; the bare relative path would fail.
!include "LogicLib.nsh"
!include "${BUILD_RESOURCES_DIR}\version.nsh"

; ─── Install: write the autostart Run key ──────────────────────────────
;
; HKCU\Software\Microsoft\Windows\CurrentVersion\Run is the per-user
; autostart registry hive. We pass `--minimized` so the Electron app
; starts into the tray (handled by services/tray-manager.cjs) rather
; than popping a window on login.
;
; Using HKCU (not HKLM) matches perMachine=false in electron-builder.yml
; — we're a per-user install, so per-user autostart is correct.

!macro customInstall
  ; Clean up the old autostart key from pre-rename installs so users
  ; who upgrade from "GAIA Agent UI" don't end up with an orphaned
  ; Run entry pointing at a binary path that no longer exists.
  DeleteRegValue HKCU "Software\Microsoft\Windows\CurrentVersion\Run" "GAIA Agent UI"

  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Run" \
      "${PRODUCT_NAME}" \
      '"$INSTDIR\${PRODUCT_FILENAME}.exe" --minimized'

  ; ── Bundle Lemonade Server MSI install (issue #774) ──────────────────────
  ; Graceful-failure contract: non-zero exit codes are logged but we never
  ; Abort — GAIA install always continues. User can recover via `gaia init`.
  ;
  ; $PLUGINSDIR is NSIS's auto-cleaned temp dir, so the ~5MB bootstrap MSI
  ; does NOT persist on the user's disk after the installer exits. (The MSI
  ; itself is a small bootstrap — it fetches the Lemonade runtime on first
  ; run — see lemonade-server-minimal.msi upstream.) ${BUILD_RESOURCES_DIR}
  ; is injected by electron-builder as a makensis -D flag and resolves to
  ; the repo's installer/ directory (per directories.buildResources in
  ; electron-builder.yml). SetOutPath "$INSTDIR" at the end restores the
  ; default output directory the surrounding template expects.
  SetOutPath "$PLUGINSDIR"
  File "${BUILD_RESOURCES_DIR}\lemonade-server-minimal.msi"
  DetailPrint "Installing Lemonade Server ${LEMONADE_VERSION}..."
  ClearErrors
  ExecWait 'msiexec /i "$PLUGINSDIR\lemonade-server-minimal.msi" /qn /norestart' $0
  ${If} $0 == 0
    DetailPrint "Lemonade Server installed successfully."
  ${ElseIf} $0 == 1638
    ; ERROR_PRODUCT_VERSION — a newer Lemonade is already installed. Fine.
    DetailPrint "Lemonade Server: newer version already installed (bundled MSI skipped)."
  ${ElseIf} $0 == 3010
    ; ERROR_SUCCESS_REBOOT_REQUIRED — installed OK; reboot pending.
    DetailPrint "Lemonade Server installed (reboot pending — will apply on next restart)."
  ${Else}
    DetailPrint "Lemonade MSI install returned exit code $0 — GAIA will continue. Run 'gaia init' to retry."
  ${EndIf}
  SetOutPath "$INSTDIR"
!macroend

; ─── Uninstall: clean up the autostart Run key ─────────────────────────
;
; Note (issue #774): Lemonade Server is intentionally NOT uninstalled here.
; The bundled MSI registers Lemonade as an independent Windows product;
; users remove it via `gaia uninstall --purge-lemonade` (Python-driven,
; registry-based via msiexec /x {ProductCode}). This keeps the uninstall
; origin-agnostic — Lemonade installed via standalone MSI vs. our bundle
; uses the same removal path.

!macro customUnInstall
  DeleteRegValue HKCU "Software\Microsoft\Windows\CurrentVersion\Run" \
      "${PRODUCT_NAME}"
  ; Also clean up the old pre-rename autostart key in case the user
  ; is uninstalling without ever having upgraded through the rename.
  DeleteRegValue HKCU "Software\Microsoft\Windows\CurrentVersion\Run" \
      "GAIA Agent UI"

  ; Optional cleanup deletes the entire shared GAIA home, including other
  ; installations' runtimes. Interactive and silent defaults preserve it.
  ;
  ; Uses a relative jump (IDNO +2) instead of named labels to avoid
  ; label-collision risk if electron-builder ever expands this macro
  ; more than once.
  MessageBox MB_YESNO|MB_ICONQUESTION|MB_DEFBUTTON2 \
      "Delete ALL files in $PROFILE\.gaia?$\r$\n$\r$\nThis includes chats, documents, custom agents, skills, connector sign-ins and permissions, memory, MCP server settings, config, logs, and shared Python and terminal runtimes.$\r$\n$\r$\nOther GAIA installations using this folder will stop working. This cannot be undone. Choose No to keep everything." \
      /SD IDNO IDNO +2
  RmDir /r "$PROFILE\.gaia"
!macroend
