; Copyright(C) 2025-2026 Advanced Micro Devices, Inc. All rights reserved.
; SPDX-License-Identifier: MIT
;
; One-click installer for the flagship GAIA agent.
;
; Ships two frozen binaries and nothing else the user has to think about:
;   gaia-tui.exe    the Go terminal UI
;   gaia-agent.exe  the frozen Python agent (stdio JSONL by default; --host/--port
;                   serves the REST surface -- see packaging/entry.py)
; plus Lemonade Server, installed from a bundled MSI during setup.
;
; This is a NEW artifact, deliberately separate from the Electron Agent UI's
; electron-builder/NSIS pipeline (installer/nsis/installer.nsh). That one is
; generated by electron-builder and hooks its template via customInstall; this
; one has no Electron and no generator, so it is a plain standalone script. The
; Lemonade block below is copied from it on purpose, including the
; graceful-failure contract -- see the comment there.
;
; Defines supplied by installer/tui/build.ps1:
;   GAIA_VERSION      bundle version (binaries.lock.json agentVersion)
;   GAIA_VERSION_4    the same, padded to NSIS's required four-part form
;   LEMONADE_VERSION  version of the bundled MSI, for the progress message
;   STAGE_DIR         directory holding the verified payload to pack
;   OUT_FILE          artifact path to write
;   LICENSE_FILE      repo LICENSE.md

Unicode true

!include "MUI2.nsh"
!include "LogicLib.nsh"
!include "FileFunc.nsh"

!ifndef GAIA_VERSION
  !error "GAIA_VERSION is not defined -- build via installer/tui/build.ps1, not makensis directly."
!endif
!ifndef STAGE_DIR
  !error "STAGE_DIR is not defined -- build via installer/tui/build.ps1, not makensis directly."
!endif
!ifndef LEMONADE_VERSION
  !error "LEMONADE_VERSION is not defined -- build via installer/tui/build.ps1, not makensis directly."
!endif

; Shown in the installer chrome and as the shortcut name.
!define PRODUCT_NAME      "GAIA"
; Shown in Add/Remove Programs. The Electron Agent UI also registers itself as
; plain "GAIA" (publisher "AMD AI Group"), so an identical row here left a user
; with two entries and no way to tell which was which. "Agent" is the product
; noun this repo already uses for the flagship, so it disambiguates without
; reading as a lesser add-on.
!define ARP_DISPLAY_NAME  "GAIA Agent"
!define PRODUCT_PUBLISHER "Advanced Micro Devices, Inc."
!define UNINST_KEY        "Software\Microsoft\Windows\CurrentVersion\Uninstall\GAIA"

Name "${PRODUCT_NAME} ${GAIA_VERSION}"
OutFile "${OUT_FILE}"
; Per-user install: no elevation prompt, and it matches the Agent UI's
; perMachine=false. The Lemonade MSI still elevates on its own if it needs to.
RequestExecutionLevel user
InstallDir "$LOCALAPPDATA\Programs\GAIA"
InstallDirRegKey HKCU "Software\GAIA" "InstallDir"
SetCompressor /SOLID lzma
ShowInstDetails show
ShowUnInstDetails show

VIProductVersion "${GAIA_VERSION_4}"
VIAddVersionKey "ProductName"     "${PRODUCT_NAME}"
VIAddVersionKey "CompanyName"     "${PRODUCT_PUBLISHER}"
VIAddVersionKey "LegalCopyright"  "Copyright (C) 2026 ${PRODUCT_PUBLISHER}"
VIAddVersionKey "FileDescription" "GAIA flagship agent installer"
VIAddVersionKey "FileVersion"     "${GAIA_VERSION}"
VIAddVersionKey "ProductVersion"  "${GAIA_VERSION}"

!define MUI_ABORTWARNING
; The GAIA robot-head mark, carrying 16/32/48/256 so Explorer, the taskbar and
; Alt-Tab each get a size they do not have to rescale. Copied into this
; installer rather than referenced from the Agent UI's tree, so the two cannot
; break each other.
!define MUI_ICON   "${STAGE_DIR}\gaia.ico"
!define MUI_UNICON "${STAGE_DIR}\gaia.ico"
!define MUI_FINISHPAGE_RUN_TEXT "Start GAIA now"
!define MUI_FINISHPAGE_RUN_FUNCTION LaunchGaia
!define MUI_FINISHPAGE_RUN

!insertmacro MUI_PAGE_LICENSE "${LICENSE_FILE}"
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "English"

; ─── Which console the TUI opens in ────────────────────────────────────
;
; Windows Terminal when it is present, the legacy console host only as a
; fallback. This is not cosmetic: conhost has no truecolor, so the TUI's
; lipgloss styling and its syntax highlighting collapse to flat, mostly
; uncoloured text and the app looks broken on first launch.
;
; wt.exe normally lives behind an App Execution Alias in WindowsApps, which is
; on PATH — but that alias can be turned off, so SearchPath is tried first and
; the literal path second. $R2 is left empty when neither resolves.
;
; The TUI is a console program, so a bare Exec would attach it to the
; installer's hidden console and no window would ever appear; both branches
; below open a real one.
; $R2 = Windows Terminal, or "" when it is not available.
; $R3 = the PowerShell command line that actually runs the TUI.
;
; PowerShell rather than cmd.exe is the shell the agent is expected to be used
; alongside, and it is what a user dropping out of the TUI should land in. The
; path is wrapped in PowerShell single quotes (NSIS $\' ) so an install
; directory containing spaces still resolves as one argument; -NoProfile keeps
; a slow or noisy user profile out of the launch path.
Function ResolveTerminal
  StrCpy $R2 ""
  SearchPath $R2 "wt.exe"
  ${If} $R2 == ""
  ${AndIf} ${FileExists} "$LOCALAPPDATA\Microsoft\WindowsApps\wt.exe"
    StrCpy $R2 "$LOCALAPPDATA\Microsoft\WindowsApps\wt.exe"
  ${EndIf}
  StrCpy $R3 '-NoLogo -NoProfile -Command "& $\'$INSTDIR\gaia-tui.exe$\'"'
FunctionEnd

Function LaunchGaia
  Call ResolveTerminal
  ${If} $R2 != ""
    Exec '"$R2" "$SYSDIR\WindowsPowerShell\v1.0\powershell.exe" $R3'
  ${Else}
    Exec '"$SYSDIR\WindowsPowerShell\v1.0\powershell.exe" $R3'
  ${EndIf}
FunctionEnd

; ---------------------------------------------------------------------------

; Windows refuses to delete a running .exe, so a failed Delete of an existing
; binary means GAIA is open. Checking up front turns "File: cannot write" (an
; abort halfway through, with a half-written install left behind) into one
; sentence naming what to close.
;
; No retry loop: a relative MessageBox jump would have to count instructions
; across two expansions of this macro, and miscounting it silently jumps
; somewhere else. Aborting with one clear sentence is worth more than a Retry
; button here.
!macro EnsureNotRunning path
  ${If} ${FileExists} "${path}"
    ClearErrors
    Delete "${path}"
    ${If} ${Errors}
      StrCpy $R1 "${path}"
      DetailPrint "Cannot replace $R1 -- it is in use."
      MessageBox MB_OK|MB_ICONEXCLAMATION "GAIA is still running, so its files cannot be replaced.$\r$\n$\r$\nClose every GAIA window and terminal, then run this installer again.$\r$\n$\r$\n$R1" /SD IDOK
      Abort "GAIA is still running -- close it and run this installer again."
    ${EndIf}
  ${EndIf}
!macroend

Section "GAIA" SecMain
  SectionIn RO

  ; This installer is per-user (RequestExecutionLevel user), so a directory like
  ; C:\Program Files is not writable and every File below silently fails. The
  ; registry and shortcut writes that follow go to HKCU and the Desktop, which
  ; ARE writable, so they succeeded -- leaving an Add/Remove entry and a Desktop
  ; icon for a product that was never installed, and no uninstaller to remove
  ; either. Checked here so a bad directory is refused while it is still just a
  ; wrong answer on the previous page.
  ClearErrors
  SetOutPath "$INSTDIR"
  ${If} ${Errors}
    DetailPrint "Cannot write to $INSTDIR."
    MessageBox MB_OK|MB_ICONSTOP "GAIA cannot be installed into:$\r$\n$\r$\n$INSTDIR$\r$\n$\r$\nThat folder is not writable by your account. This installer does not ask for administrator rights, so choose a folder you own -- the default is $LOCALAPPDATA\Programs\GAIA.$\r$\n$\r$\nNothing was installed." /SD IDOK
    Abort "Cannot write to $INSTDIR -- choose a folder your account owns."
  ${EndIf}

  !insertmacro EnsureNotRunning "$INSTDIR\gaia-tui.exe"
  !insertmacro EnsureNotRunning "$INSTDIR\gaia-agent.exe"

  File "${STAGE_DIR}\gaia-tui.exe"
  File "${STAGE_DIR}\gaia-agent.exe"
  File "${STAGE_DIR}\pathmgr.ps1"
  ; Installed so the shortcuts can name an icon explicitly. gaia-tui.exe now
  ; embeds the same mark (tui/cmd/gaia/rsrc_windows_*.syso), which is what makes
  ; Explorer, the taskbar and Alt-Tab draw it -- a shortcut icon alone would not.
  File "${STAGE_DIR}\gaia.ico"

  ; Belt and braces on the outcome rather than the error flag: NSIS's File keeps
  ; going after a failed write, and everything below (registry, shortcuts, PATH)
  ; would then advertise an install that is not on disk.
  ${IfNot} ${FileExists} "$INSTDIR\gaia-tui.exe"
  ${OrIfNot} ${FileExists} "$INSTDIR\gaia-agent.exe"
    DetailPrint "The GAIA binaries were not written to $INSTDIR."
    MessageBox MB_OK|MB_ICONSTOP "GAIA's files could not be written to:$\r$\n$\r$\n$INSTDIR$\r$\n$\r$\nCheck free space and folder permissions, then try again.$\r$\n$\r$\nNothing was installed." /SD IDOK
    Abort "The GAIA binaries were not written to $INSTDIR."
  ${EndIf}

  WriteRegStr HKCU "Software\GAIA" "InstallDir" "$INSTDIR"
  WriteRegStr HKCU "Software\GAIA" "Version"    "${GAIA_VERSION}"

  ; --- Add/Remove Programs -------------------------------------------------
  WriteUninstaller "$INSTDIR\Uninstall.exe"
  WriteRegStr   HKCU "${UNINST_KEY}" "DisplayName"     "${ARP_DISPLAY_NAME}"
  WriteRegStr   HKCU "${UNINST_KEY}" "DisplayVersion"  "${GAIA_VERSION}"
  WriteRegStr   HKCU "${UNINST_KEY}" "Publisher"       "${PRODUCT_PUBLISHER}"
  WriteRegStr   HKCU "${UNINST_KEY}" "DisplayIcon"     "$INSTDIR\gaia.ico"
  WriteRegStr   HKCU "${UNINST_KEY}" "UninstallString" '"$INSTDIR\Uninstall.exe"'
  WriteRegStr   HKCU "${UNINST_KEY}" "InstallLocation" "$INSTDIR"
  WriteRegDWORD HKCU "${UNINST_KEY}" "NoModify" 1
  WriteRegDWORD HKCU "${UNINST_KEY}" "NoRepair" 1
  ${GetSize} "$INSTDIR" "/S=0K" $0 $1 $2
  IntFmt $0 "0x%08X" $0
  WriteRegDWORD HKCU "${UNINST_KEY}" "EstimatedSize" "$0"

  ; --- Shortcuts -----------------------------------------------------------
  ; Resolved at install time, so a machine with Windows Terminal gets a
  ; shortcut into it and one without still gets a working console. The icon is
  ; taken from gaia-tui.exe either way, so the shortcut looks like GAIA rather
  ; than like whichever terminal is hosting it.
  ; Both shortcuts target powershell.exe -- a real file in System32 -- and never
  ; wt.exe.
  ;
  ; wt.exe in WindowsApps is a zero-byte App Execution Alias (a reparse point),
  ; not a binary. A .lnk pointing at one is fragile: the alias can be switched
  ; off in Settings, and tools that read the shortcut back see a target that is
  ; not a real file. Windows 11 already uses Windows Terminal as the default
  ; console host, so launching powershell.exe lands in Windows Terminal anyway
  ; -- the truecolor this was for -- without depending on the alias at all.
  Call ResolveTerminal
  CreateDirectory "$SMPROGRAMS\GAIA"
  CreateShortCut "$SMPROGRAMS\GAIA\GAIA.lnk" "$SYSDIR\WindowsPowerShell\v1.0\powershell.exe" "$R3" "$INSTDIR\gaia.ico" 0
  CreateShortCut "$DESKTOP\GAIA.lnk"          "$SYSDIR\WindowsPowerShell\v1.0\powershell.exe" "$R3" "$INSTDIR\gaia.ico" 0

  ; Read back rather than trusting CreateShortCut: a shortcut with an empty
  ; target is indistinguishable from a working one until someone clicks it.
  ${IfNot} ${FileExists} "$DESKTOP\GAIA.lnk"
  ${OrIfNot} ${FileExists} "$SMPROGRAMS\GAIA\GAIA.lnk"
    DetailPrint "WARNING: a shortcut was not created."
    MessageBox MB_OK|MB_ICONEXCLAMATION "GAIA installed, but one of its shortcuts could not be created.$\r$\n$\r$\nRun it from a terminal instead:$\r$\n$\r$\n  gaia-tui" /SD IDOK
  ${EndIf}

  ; --- PATH ----------------------------------------------------------------
  ; This entry is what makes the flagship launchable at all, not a convenience:
  ; the catalog entry declares BinaryPath "gaia-agent" and DiscoverBinaries()
  ; resolves it with exec.LookPath, so gaia-tui finds its agent through PATH.
  DetailPrint "Adding $INSTDIR to your PATH..."
  nsExec::ExecToLog '"$SYSDIR\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -NonInteractive -ExecutionPolicy Bypass -File "$INSTDIR\pathmgr.ps1" -Action Add -Directory "$INSTDIR"'
  Pop $0
  ${If} $0 != 0
    ; Loud, not fatal: the files installed fine and the shortcut works, but
    ; `gaia-tui` from a terminal will not -- and leaving the user to discover
    ; that on their own is worse than the files not being there.
    DetailPrint "WARNING: could not update your PATH (exit code $0)."
    ; /SD IDOK so an unattended install reports this in the log and moves on
    ; instead of hanging on a modal nobody is there to dismiss.
    MessageBox MB_OK|MB_ICONEXCLAMATION "GAIA installed, but your PATH could not be updated (exit code $0).$\r$\n$\r$\nThe Start Menu shortcut still works. To run gaia-tui from a terminal, add this folder to your PATH by hand:$\r$\n$\r$\n$INSTDIR" /SD IDOK
  ${EndIf}

  ; --- Bundled Lemonade Server MSI (issue #774) ----------------------------
  ; Same graceful-failure contract as the Agent UI installer: a non-zero exit
  ; code is reported but never Aborts -- the GAIA install always completes and
  ; the user can recover with `gaia init`. $PLUGINSDIR is auto-cleaned, so the
  ; ~5MB bootstrap MSI does not persist on disk.
  SetOutPath "$PLUGINSDIR"
  File "${STAGE_DIR}\lemonade-server-minimal.msi"
  DetailPrint "Installing Lemonade Server ${LEMONADE_VERSION}..."
  ClearErrors
  ExecWait 'msiexec /i "$PLUGINSDIR\lemonade-server-minimal.msi" /qn /norestart' $0
  ${If} $0 == 0
    DetailPrint "Lemonade Server installed successfully."
  ${ElseIf} $0 == 1638
    DetailPrint "Lemonade Server: newer version already installed (bundled MSI skipped)."
  ${ElseIf} $0 == 3010
    DetailPrint "Lemonade Server installed (reboot pending -- applies on next restart)."
  ${Else}
    DetailPrint "Lemonade MSI install returned exit code $0 -- GAIA will continue. Run 'gaia init' to retry."
  ${EndIf}
  SetOutPath "$INSTDIR"
SectionEnd

; ---------------------------------------------------------------------------

Section "Uninstall"
  ; Refuse before removing anything, the same way installing over a running GAIA
  ; is refused.
  ;
  ; Deleting the binaries FIRST is the liveness test -- Windows will not delete a
  ; running .exe. Doing it in this order matters: the previous version swept the
  ; files, then PATH, then the registry, then noticed the survivor. That left a
  ; machine with gaia-tui.exe still on disk but no PATH entry, no Add/Remove row
  ; and no Uninstall.exe -- an orphan with nothing left to remove it. Better to
  ; touch nothing and let the user close GAIA and run it again.
  ; Guarded on existence so a RETRY works: a second uninstall must not trip over
  ; a file the first one already removed. gaia-tui is tested before gaia-agent
  ; because it is the parent -- if the UI is running, this aborts having touched
  ; nothing at all.
  ;
  ; $R4 records the outcome because LogicLib's ${Errors} is IfErrors, which
  ; CLEARS the flag as it reads it. Testing it twice therefore always came back
  ; false the second time: the abort never fired, and an uninstall over a running
  ; GAIA stripped PATH, the Add/Remove row and Uninstall.exe while the binaries
  ; survived -- an orphan with nothing left to remove it.
  StrCpy $R4 "0"
  ${If} ${FileExists} "$INSTDIR\gaia-tui.exe"
    ClearErrors
    Delete "$INSTDIR\gaia-tui.exe"
    ${If} ${Errors}
      StrCpy $R4 "1"
    ${EndIf}
  ${EndIf}
  ${If} $R4 == "0"
  ${AndIf} ${FileExists} "$INSTDIR\gaia-agent.exe"
    ClearErrors
    Delete "$INSTDIR\gaia-agent.exe"
    ${If} ${Errors}
      StrCpy $R4 "1"
    ${EndIf}
  ${EndIf}
  ${If} $R4 == "1"
    DetailPrint "GAIA is still running -- nothing was removed."
    MessageBox MB_OK|MB_ICONEXCLAMATION "GAIA is still running, so it cannot be uninstalled.$\r$\n$\r$\nClose every GAIA window and terminal, then uninstall again.$\r$\n$\r$\nNothing has been removed." /SD IDOK
    Abort "GAIA is still running -- close it and uninstall again."
  ${EndIf}

  ; PATH first: it needs pathmgr.ps1, which the sweep below deletes.
  ${If} ${FileExists} "$INSTDIR\pathmgr.ps1"
    DetailPrint "Removing $INSTDIR from your PATH..."
    nsExec::ExecToLog '"$SYSDIR\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -NonInteractive -ExecutionPolicy Bypass -File "$INSTDIR\pathmgr.ps1" -Action Remove -Directory "$INSTDIR"'
    Pop $0
    ${If} $0 != 0
      DetailPrint "WARNING: could not clean your PATH (exit code $0) -- remove $INSTDIR from it by hand."
    ${EndIf}
  ${EndIf}

  ; The binaries are already gone (deleted above as the liveness test).
  Delete "$INSTDIR\pathmgr.ps1"
  Delete "$INSTDIR\gaia.ico"
  Delete "$INSTDIR\Uninstall.exe"
  ; Left behind by the updater's swap when a replaced binary was still locked.
  Delete "$INSTDIR\gaia-tui.exe.old"
  Delete "$INSTDIR\gaia-agent.exe.old"
  ; Written by `gaia-tui update` after a swap, so it exists only on a machine
  ; that has updated at least once -- which is why a fresh install uninstalled
  ; cleanly while an updated one left this behind and kept the folder alive.
  Delete "$INSTDIR\.installed"
  RMDir "$INSTDIR"

  ; RMDir above is non-recursive on purpose: $INSTDIR is user-chosen, and a
  ; recursive delete of a directory someone pointed at their Documents folder is
  ; not a risk worth taking. That means anything unaccounted for keeps the
  ; folder alive, so say what survived instead of reporting a clean uninstall
  ; over it.
  ${If} ${FileExists} "$INSTDIR\*.*"
    DetailPrint "Some files in $INSTDIR were not created by this installer and were left alone."
    MessageBox MB_OK|MB_ICONINFORMATION "GAIA was uninstalled, but $INSTDIR still holds files this installer did not put there, so it was left in place.$\r$\n$\r$\nDelete it by hand if you do not need it." /SD IDOK
  ${EndIf}

  Delete "$SMPROGRAMS\GAIA\GAIA.lnk"
  RMDir  "$SMPROGRAMS\GAIA"
  Delete "$DESKTOP\GAIA.lnk"

  DeleteRegKey HKCU "${UNINST_KEY}"
  DeleteRegKey HKCU "Software\GAIA"

  ; Lemonade Server is intentionally NOT uninstalled -- the MSI registers it as
  ; an independent Windows product, removed the same way whether it arrived from
  ; this bundle or a standalone download. Same call the Agent UI installer makes.

  ; Default No so a user keeps chats, memory, and skills unless they opt in.
  ; /SD IDNO makes an unattended uninstall keep data.
  MessageBox MB_YESNO|MB_ICONQUESTION "Also remove your GAIA data (chats, memory, skills, documents)?$\r$\n$\r$\nThis cannot be undone." /SD IDNO IDNO +2
  RMDir /r "$PROFILE\.gaia"
SectionEnd
