; Copyright(C) 2025-2026 Advanced Micro Devices, Inc. All rights reserved.
; SPDX-License-Identifier: MIT
;
; One-click installer for the flagship GAIA agent.
;
; Ships two frozen binaries and nothing else the user has to think about:
;   gaia-tui.exe    the Go terminal UI
;   gaia-agent.exe  the frozen Python agent (stdio JSONL by default; --host/--port
;                   serves the REST surface -- see packaging/entry.py)
; plus Lemonade Server, installed from a bundled MSI during setup.
;
; This is a NEW artifact, deliberately separate from the Electron Agent UI's
; electron-builder/NSIS pipeline (installer/nsis/installer.nsh). That one is
; generated by electron-builder and hooks its template via customInstall; this
; one has no Electron and no generator, so it is a plain standalone script. The
; Lemonade block below is copied from it on purpose, including the
; graceful-failure contract -- see the comment there.
;
; Defines supplied by installer/tui/build.ps1:
;   GAIA_VERSION      bundle version (binaries.lock.json agentVersion)
;   GAIA_VERSION_4    the same, padded to NSIS's required four-part form
;   LEMONADE_VERSION  version of the bundled MSI, for the progress message
;   STAGE_DIR         directory holding the verified payload to pack
;   OUT_FILE          artifact path to write
;   LICENSE_FILE      repo LICENSE.md

Unicode true

!include "MUI2.nsh"
!include "LogicLib.nsh"
!include "FileFunc.nsh"

!ifndef GAIA_VERSION
  !error "GAIA_VERSION is not defined -- build via installer/tui/build.ps1, not makensis directly."
!endif
!ifndef STAGE_DIR
  !error "STAGE_DIR is not defined -- build via installer/tui/build.ps1, not makensis directly."
!endif
!ifndef LEMONADE_VERSION
  !error "LEMONADE_VERSION is not defined -- build via installer/tui/build.ps1, not makensis directly."
!endif

!define PRODUCT_NAME      "GAIA"
!define PRODUCT_PUBLISHER "Advanced Micro Devices, Inc."
!define UNINST_KEY        "Software\Microsoft\Windows\CurrentVersion\Uninstall\GAIA"

Name "${PRODUCT_NAME} ${GAIA_VERSION}"
OutFile "${OUT_FILE}"
; Per-user install: no elevation prompt, and it matches the Agent UI's
; perMachine=false. The Lemonade MSI still elevates on its own if it needs to.
RequestExecutionLevel user
InstallDir "$LOCALAPPDATA\Programs\GAIA"
InstallDirRegKey HKCU "Software\GAIA" "InstallDir"
SetCompressor /SOLID lzma
ShowInstDetails show
ShowUnInstDetails show

VIProductVersion "${GAIA_VERSION_4}"
VIAddVersionKey "ProductName"     "${PRODUCT_NAME}"
VIAddVersionKey "CompanyName"     "${PRODUCT_PUBLISHER}"
VIAddVersionKey "LegalCopyright"  "Copyright (C) 2026 ${PRODUCT_PUBLISHER}"
VIAddVersionKey "FileDescription" "GAIA flagship agent installer"
VIAddVersionKey "FileVersion"     "${GAIA_VERSION}"
VIAddVersionKey "ProductVersion"  "${GAIA_VERSION}"

!define MUI_ABORTWARNING
!define MUI_ICON   "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"
!define MUI_FINISHPAGE_RUN_TEXT "Start GAIA now"
!define MUI_FINISHPAGE_RUN_FUNCTION LaunchGaia
!define MUI_FINISHPAGE_RUN

!insertmacro MUI_PAGE_LICENSE "${LICENSE_FILE}"
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "English"

; ─── Which console the TUI opens in ────────────────────────────────────
;
; Windows Terminal when it is present, the legacy console host only as a
; fallback. This is not cosmetic: conhost has no truecolor, so the TUI's
; lipgloss styling and its syntax highlighting collapse to flat, mostly
; uncoloured text and the app looks broken on first launch.
;
; wt.exe normally lives behind an App Execution Alias in WindowsApps, which is
; on PATH — but that alias can be turned off, so SearchPath is tried first and
; the literal path second. $R2 is left empty when neither resolves.
;
; The TUI is a console program, so a bare Exec would attach it to the
; installer's hidden console and no window would ever appear; both branches
; below open a real one.
; $R2 = Windows Terminal, or "" when it is not available.
; $R3 = the PowerShell command line that actually runs the TUI.
;
; PowerShell rather than cmd.exe is the shell the agent is expected to be used
; alongside, and it is what a user dropping out of the TUI should land in. The
; path is wrapped in PowerShell single quotes (NSIS $\' ) so an install
; directory containing spaces still resolves as one argument; -NoProfile keeps
; a slow or noisy user profile out of the launch path.
Function ResolveTerminal
  StrCpy $R2 ""
  SearchPath $R2 "wt.exe"
  ${If} $R2 == ""
  ${AndIf} ${FileExists} "$LOCALAPPDATA\Microsoft\WindowsApps\wt.exe"
    StrCpy $R2 "$LOCALAPPDATA\Microsoft\WindowsApps\wt.exe"
  ${EndIf}
  StrCpy $R3 '-NoLogo -NoProfile -Command "& $\'$INSTDIR\gaia-tui.exe$\'"'
FunctionEnd

Function LaunchGaia
  Call ResolveTerminal
  ${If} $R2 != ""
    Exec '"$R2" "$SYSDIR\WindowsPowerShell\v1.0\powershell.exe" $R3'
  ${Else}
    Exec '"$SYSDIR\WindowsPowerShell\v1.0\powershell.exe" $R3'
  ${EndIf}
FunctionEnd

; ---------------------------------------------------------------------------

; Windows refuses to delete a running .exe, so a failed Delete of an existing
; binary means GAIA is open. Checking up front turns "File: cannot write" (an
; abort halfway through, with a half-written install left behind) into one
; sentence naming what to close.
;
; No retry loop: a relative MessageBox jump would have to count instructions
; across two expansions of this macro, and miscounting it silently jumps
; somewhere else. Aborting with one clear sentence is worth more than a Retry
; button here.
!macro EnsureNotRunning path
  ${If} ${FileExists} "${path}"
    ClearErrors
    Delete "${path}"
    ${If} ${Errors}
      StrCpy $R1 "${path}"
      DetailPrint "Cannot replace $R1 -- it is in use."
      MessageBox MB_OK|MB_ICONEXCLAMATION "GAIA is still running, so its files cannot be replaced.$\r$\n$\r$\nClose every GAIA window and terminal, then run this installer again.$\r$\n$\r$\n$R1" /SD IDOK
      Abort "GAIA is still running -- close it and run this installer again."
    ${EndIf}
  ${EndIf}
!macroend

Section "GAIA" SecMain
  SectionIn RO
  SetOutPath "$INSTDIR"

  !insertmacro EnsureNotRunning "$INSTDIR\gaia-tui.exe"
  !insertmacro EnsureNotRunning "$INSTDIR\gaia-agent.exe"

  File "${STAGE_DIR}\gaia-tui.exe"
  File "${STAGE_DIR}\gaia-agent.exe"
  File "${STAGE_DIR}\pathmgr.ps1"

  WriteRegStr HKCU "Software\GAIA" "InstallDir" "$INSTDIR"
  WriteRegStr HKCU "Software\GAIA" "Version"    "${GAIA_VERSION}"

  ; --- Add/Remove Programs -------------------------------------------------
  WriteUninstaller "$INSTDIR\Uninstall.exe"
  WriteRegStr   HKCU "${UNINST_KEY}" "DisplayName"     "${PRODUCT_NAME}"
  WriteRegStr   HKCU "${UNINST_KEY}" "DisplayVersion"  "${GAIA_VERSION}"
  WriteRegStr   HKCU "${UNINST_KEY}" "Publisher"       "${PRODUCT_PUBLISHER}"
  WriteRegStr   HKCU "${UNINST_KEY}" "DisplayIcon"     "$INSTDIR\gaia-tui.exe"
  WriteRegStr   HKCU "${UNINST_KEY}" "UninstallString" '"$INSTDIR\Uninstall.exe"'
  WriteRegStr   HKCU "${UNINST_KEY}" "InstallLocation" "$INSTDIR"
  WriteRegDWORD HKCU "${UNINST_KEY}" "NoModify" 1
  WriteRegDWORD HKCU "${UNINST_KEY}" "NoRepair" 1
  ${GetSize} "$INSTDIR" "/S=0K" $0 $1 $2
  IntFmt $0 "0x%08X" $0
  WriteRegDWORD HKCU "${UNINST_KEY}" "EstimatedSize" "$0"

  ; --- Shortcuts -----------------------------------------------------------
  ; Resolved at install time, so a machine with Windows Terminal gets a
  ; shortcut into it and one without still gets a working console. The icon is
  ; taken from gaia-tui.exe either way, so the shortcut looks like GAIA rather
  ; than like whichever terminal is hosting it.
  Call ResolveTerminal
  CreateDirectory "$SMPROGRAMS\GAIA"
  ${If} $R2 != ""
    DetailPrint "Shortcuts will open GAIA in Windows Terminal (PowerShell)."
    CreateShortCut "$SMPROGRAMS\GAIA\GAIA.lnk" "$R2" '"$SYSDIR\WindowsPowerShell\v1.0\powershell.exe" $R3' "$INSTDIR\gaia-tui.exe" 0
    CreateShortCut "$DESKTOP\GAIA.lnk"          "$R2" '"$SYSDIR\WindowsPowerShell\v1.0\powershell.exe" $R3' "$INSTDIR\gaia-tui.exe" 0
  ${Else}
    ; No Windows Terminal: PowerShell still hosts it, just in whatever console
    ; the system provides. A working shortcut beats none.
    DetailPrint "Windows Terminal not found — shortcuts will use PowerShell in the system console."
    CreateShortCut "$SMPROGRAMS\GAIA\GAIA.lnk" "$SYSDIR\WindowsPowerShell\v1.0\powershell.exe" "$R3" "$INSTDIR\gaia-tui.exe" 0
    CreateShortCut "$DESKTOP\GAIA.lnk"          "$SYSDIR\WindowsPowerShell\v1.0\powershell.exe" "$R3" "$INSTDIR\gaia-tui.exe" 0
  ${EndIf}

  ; --- PATH ----------------------------------------------------------------
  ; This entry is what makes the flagship launchable at all, not a convenience:
  ; the catalog entry declares BinaryPath "gaia-agent" and DiscoverBinaries()
  ; resolves it with exec.LookPath, so gaia-tui finds its agent through PATH.
  DetailPrint "Adding $INSTDIR to your PATH..."
  nsExec::ExecToLog '"$SYSDIR\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -NonInteractive -ExecutionPolicy Bypass -File "$INSTDIR\pathmgr.ps1" -Action Add -Directory "$INSTDIR"'
  Pop $0
  ${If} $0 != 0
    ; Loud, not fatal: the files installed fine and the shortcut works, but
    ; `gaia-tui` from a terminal will not -- and leaving the user to discover
    ; that on their own is worse than the files not being there.
    DetailPrint "WARNING: could not update your PATH (exit code $0)."
    ; /SD IDOK so an unattended install reports this in the log and moves on
    ; instead of hanging on a modal nobody is there to dismiss.
    MessageBox MB_OK|MB_ICONEXCLAMATION "GAIA installed, but your PATH could not be updated (exit code $0).$\r$\n$\r$\nThe Start Menu shortcut still works. To run gaia-tui from a terminal, add this folder to your PATH by hand:$\r$\n$\r$\n$INSTDIR" /SD IDOK
  ${EndIf}

  ; --- Bundled Lemonade Server MSI (issue #774) ----------------------------
  ; Same graceful-failure contract as the Agent UI installer: a non-zero exit
  ; code is reported but never Aborts -- the GAIA install always completes and
  ; the user can recover with `gaia init`. $PLUGINSDIR is auto-cleaned, so the
  ; ~5MB bootstrap MSI does not persist on disk.
  SetOutPath "$PLUGINSDIR"
  File "${STAGE_DIR}\lemonade-server-minimal.msi"
  DetailPrint "Installing Lemonade Server ${LEMONADE_VERSION}..."
  ClearErrors
  ExecWait 'msiexec /i "$PLUGINSDIR\lemonade-server-minimal.msi" /qn /norestart' $0
  ${If} $0 == 0
    DetailPrint "Lemonade Server installed successfully."
  ${ElseIf} $0 == 1638
    DetailPrint "Lemonade Server: newer version already installed (bundled MSI skipped)."
  ${ElseIf} $0 == 3010
    DetailPrint "Lemonade Server installed (reboot pending -- applies on next restart)."
  ${Else}
    DetailPrint "Lemonade MSI install returned exit code $0 -- GAIA will continue. Run 'gaia init' to retry."
  ${EndIf}
  SetOutPath "$INSTDIR"
SectionEnd

; ---------------------------------------------------------------------------

Section "Uninstall"
  ; PATH first: it needs pathmgr.ps1, which the sweep below deletes.
  ${If} ${FileExists} "$INSTDIR\pathmgr.ps1"
    DetailPrint "Removing $INSTDIR from your PATH..."
    nsExec::ExecToLog '"$SYSDIR\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -NonInteractive -ExecutionPolicy Bypass -File "$INSTDIR\pathmgr.ps1" -Action Remove -Directory "$INSTDIR"'
    Pop $0
    ${If} $0 != 0
      DetailPrint "WARNING: could not clean your PATH (exit code $0) -- remove $INSTDIR from it by hand."
    ${EndIf}
  ${EndIf}

  Delete "$INSTDIR\gaia-tui.exe"
  Delete "$INSTDIR\gaia-agent.exe"
  Delete "$INSTDIR\pathmgr.ps1"
  Delete "$INSTDIR\Uninstall.exe"
  ; Left behind by the updater's swap when a replaced binary was still locked.
  Delete "$INSTDIR\gaia-tui.exe.old"
  Delete "$INSTDIR\gaia-agent.exe.old"
  RMDir "$INSTDIR"

  ; Windows cannot delete a running .exe, so a survivor here means GAIA was open
  ; and this uninstall was partial. Saying so beats an "uninstalled" dialog over
  ; a folder that still has the binaries in it.
  ${If} ${FileExists} "$INSTDIR\gaia-tui.exe"
  ${OrIf} ${FileExists} "$INSTDIR\gaia-agent.exe"
    DetailPrint "WARNING: some files could not be removed -- GAIA was running."
    MessageBox MB_OK|MB_ICONEXCLAMATION "Some GAIA files could not be removed because GAIA was still running.$\r$\n$\r$\nClose every GAIA window and terminal, then delete this folder by hand:$\r$\n$\r$\n$INSTDIR" /SD IDOK
  ${EndIf}

  Delete "$SMPROGRAMS\GAIA\GAIA.lnk"
  RMDir  "$SMPROGRAMS\GAIA"
  Delete "$DESKTOP\GAIA.lnk"

  DeleteRegKey HKCU "${UNINST_KEY}"
  DeleteRegKey HKCU "Software\GAIA"

  ; Lemonade Server is intentionally NOT uninstalled -- the MSI registers it as
  ; an independent Windows product, removed the same way whether it arrived from
  ; this bundle or a standalone download. Same call the Agent UI installer makes.

  ; Default No so a user keeps chats, memory, and skills unless they opt in.
  ; /SD IDNO makes an unattended uninstall keep data.
  MessageBox MB_YESNO|MB_ICONQUESTION "Also remove your GAIA data (chats, memory, skills, documents)?$\r$\n$\r$\nThis cannot be undone." /SD IDNO IDNO +2
  RMDir /r "$PROFILE\.gaia"
SectionEnd
